# Generated by Django 4.0.5 on 2022-06-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('YIGIT', 'Yigit'), ('QIZ', 'Qiz')], max_length=50)),
                ('profile_pic', models.FileField(upload_to='')),
                ('phone_number', models.CharField(max_length=9)),
                ('coming_day', models.DateTimeField()),
                ('first_lesson_day', models.DateTimeField()),
                ('in_queue', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('group', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
